---
issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
    - path: utils/test_matchers
      linters:
        - errcheck

linters-settings:
  errcheck:
    exclude: scripts/errcheck_excludes.txt
